[General]
Callsign=your_callsign_here
Timeout=180			# Transmitter timeout in seconds. Default is: 120s
Duplex=0			# Is this station Simplex or Duplex. DVMega is simplex. Default is: 1
RFModeHang=10     		# Time to stay in mode after RF-receiption Default is: 10s
NetModeHang=3     		# Time to stay in mode after Network-receiption Default is: 3s
Display=None			# Contains the name of the display section used
Daemon=0			# Run in background
Id=your_dmrid_plus_suffix (9 digits)

[Info]
RXFrequency=434500000		# Receiver frequency in Hz Used by DVMega, reported to DMR-Master. Default is: 0Hz
TXFrequency=434500000		# Transmitter frequency in Hz. Used by DVMega, reported to DMR-Master. Default is: 0Hz
Latitude=0.0    		# if set, reported to DMR-Master, causes recognition as repeater in BrandMeister
Longitude=0.0    		# if set, reported to DMR-Master, causes recognition as repeater in BrandMeister
Height=0    			# if set, reported to DMR-Master, causes recognition as repeater in BrandMeister
Location=Nowhere
Description=Multi-Mode Repeater
URL=mmdvm.com

[DMR Id Lookup]
File=DMRIds.dat
Time=24

[Log]
# Logging levels
# 0 = No logging
# 1 = Debug
# 2 = Message
# 3 = Info
# 4 = Warning
# 5 = Error
# 6 = Fatal
DisplayLevel=1			# log Debug to console. Default is: 0 
FileLevel=0			# log Debug to file. Default is: 0
FilePath=.			# location, where the logfile is to be stored. "." means in current working directory
FileRoot=MMDVM			# Prefix of the logfile-name. In example: MMDVM-2016-12-31.log

[CW Id]
Enable=0			# Enable the CW Id
Time=10				# Time-interval for repeating CW-ID in minutes

[Modem]
Protocol=uart
UARTPort=/dev/ttyACM0
UARTSpeed=460800
TXInvert=1			# Invert TX data. Needed for some transmitters. Default is: 0
RXInvert=0			# Invert RX data. Needed for some receivers. Default is: 0
PTTInvert=0			# PTT goes low to transmit. Invert for some transmitters. Default is: 0
TXDelay=100			# Give the transmitter time to settle in ms. Default is: 100ms
DMRDelay=0			# Compensate for delay in transmitter audio chain in ms . Usually DSP based. Default is: 0.0ms
RXLevel=50			# Soft control for receive level. Not used by DVMega. Default is: 100%
TXLevel=50			# Soft Control for transmit level. Not used by DVMega. Default is: 100% 
OscOffset=0			# Tweak the Due oscillator if not using the TCXO. Default is: 0ppm
RSSIMultiplier=1
RSSIOffset=10
Debug=0


[DMR]
Enable=1			# Enable DMR repeater mode. Default is: 1
Beacons=0     			# Enable transmission of DMR-Beacons, used for DMR-Roaming
ColorCode=1   			# Color Code to use for DMR repeater access. Default is: 1
SelfOnly=0    			# If set, only own ID can operate. Default is: 0
CallHang=3    			# Time to answer in same Talk Group. Default is: 3
TXHang=4      			# Time that TX stays on transmission after DMR-over. Default is: 3
Id=260423202

[DMR Network]
Enable=1
Type=Gateway
GatewayAddress=127.0.0.1
GatewayPort=62031
LocalPort=62032
Slot2=1
Id=yourdmr_id_with_suffix (9 digits, last two: 00, 01, 02...)

[MQTT]
Host=mosquitto
Port=1883
Auth=0
Username=
Password=
Keepalive=60
Name=host
